language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - python setup.py install
  - pip install coverage

script: nosetests -v --with-coverage --cover-package=optionaldict

after_success:
  - pip install coveralls
  - coveralls
